### ISSUE TITLE
Can’t download Apps

### ISSUE THREAD

**Issue by mlgxyves** [pwn20wndstuff/Undecimus#1689]
**Describe the bug**
Ist doesn’t allow me to install Apps from the App Store.

**To Reproduce**
1. Go to the AppStore
2. Click on any App and try to download it.
4. See that it infinitely trys to download and install the App.

**Screenshots**
![E5C8E748-0553-414C-945C-93973A30184B](https://user-images.githubusercontent.com/61098650/74600634-a8776400-5094-11ea-828e-e00a2ebbee35.png)

**Device
 - iOS Version: iOS 13.3
 - iOS Device: iPhone 11 (iPhone 12,1)
 - unc0ver Version: 4.0.0

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by miguelr4720** [comment]
same here having the same problem

**Comment by miguelr4720** [comment]
try to download app un-jailbroken

**Comment by icaros7** [comment]
Same issue too. When I want to install or update via appstore, must be un-jailbreak & continue.

**Comment by fly8888** [comment]
iOS Version: iOS 13.3
iOS Device: iPhone XS
unc0ver Version: 4.0.0

too problem

**Comment by lt-fancy** [comment]
After installing the AppSync Unified tweak from "http://cydia.kiiimo.org" repo, I can update or purchase any apps from App Store.

**Comment by CoccodrillooXDS** [comment]
> After installing the AppSync Unified tweak from "http://cydia.kiiimo.org" repo, I can update or purchase any apps from App Store.

Yeah with AppSync Unified it works now, but download it from the original repo (not the cracked one):
> https://cydia.akemi.ai

(https://cydia.akemi.ai/?page/net.angelxwind.appsyncunified)

**Comment by fly8888** [comment]
I downloaded the source code, compiled, installed, did not work.




On 02/16/2020 20:12, CoccodrillooXDS wrote:

After installing the AppSync Unified tweak from "http://cydia.kiiimo.org" repo, I can update or purchase any apps from App Store.

Yeah with AppSync Unified it works now, but download it from the original repo (not the cracked one):

https://cydia.akemi.ai

(https://cydia.akemi.ai/?page/net.angelxwind.appsyncunified)

**Comment by fly8888** [comment]
Success  !install  by cydia!




On 02/16/2020 20:17, zhang wrote:
I downloaded the source code, compiled, installed, did not work.




On 02/16/2020 20:12, CoccodrillooXDS wrote:

After installing the AppSync Unified tweak from "http://cydia.kiiimo.org" repo, I can update or purchase any apps from App Store.

Yeah with AppSync Unified it works now, but download it from the original repo (not the cracked one):

https://cydia.akemi.ai

(https://cydia.akemi.ai/?page/net.angelxwind.appsyncunified)

**Comment by fly8888** [comment]
### iOS Version: iOS 13.3
### iOS Device: iPhone XS
### unc0ver Version: 4.0.0

### too problem.
### Even in unjailbreak ,appstore unable too！
### I installed AppSync ,don't work! 

I think ,maybe filesystem error!
AppStore can download app ,but can't install it.
I try install with "ipainstaller"  tool ,  error!
```
"Force installation enabled.
Analyzing iTerminal 8.21.ipa...
Installing iTerminal (v8.21)...
Failed to install iTerminal (v8.21)"
```

**Comment by fly8888** [comment]
### I find some err infomation!

```
appstored ------- 
[BYQ9B3B7E94/com.comcsoft.iTerminal:581455211] Failing installation after receiving error:
 Error Domain=IXUserPresentableErrorDomain Code=1 "This app could not be installed at this time." 
UserInfo={NSLocalizedDescription=This app could not be installed at this time., 
NSLocalizedFailureReason=Could not install at this time., NSLocalizedRecoverySuggestion=Failed 
to write iTunesMetadata data to file:///private/var/containers/Temp/Bundle/Application/196483A5-
ECA3-407F-9330-3584A88C5ADE/iTunesMetadata.plist : Error Domain=NSCocoaErrorDomain 
Code=513 "You don’t have permission to save the file “iTunesMetadata.plist” in the folder 
“196483A5-ECA3-407F-9330-3584A88C5ADE”." UserInfo=
{NSURL=file:///private/var/containers/Temp/Bundle/Application/196483A5-ECA3-407F-9330-
3584A88C5ADE/iTunesMetadata.plist, NSUserStringVariant=Folder, 
NSUnderlyingError=0x101719e10 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission 
denied"}}, NSUnderlyingError=0x1052edd90 {Error Domain=MIInstallerErrorDomain Code=24 
"Failed to write iTunesMetadata data to file:
```

###  Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “iTunesMetadata.plist” in the folder “196483A5-ECA3-407F-9330-3584A88C5ADE”.

**Comment by gabe-lucas** [comment]
Duplicate of #1688.

**Comment by gabe-lucas** [comment]
@fly8888 Have you tried a reboot and then re-jailbreaking? It may be a one off mount issue.

**Comment by fly8888** [comment]
I reboot three times. Don't work!  




On 02/17/2020 02:26, Gabriel Lucas wrote:

@fly8888 Have you tried a reboot and then re-jailbreaking? It may be a one off mount issue.

**Comment by miguelr4720** [comment]
fixed 4.0.1 :) Unc0ver

**Comment by KH12** [comment]
Fix it by used appsync on 4.0.1 😅

**Comment by fly8888** [comment]
### I can't install any new apps, including V4.0.1... Even when the phone is not jailbroken. Are there any other repair tools?

**Comment by AppInstalleriOSGH** [comment]
Same issue, I restored the rootfs and still cannot install apps using Installd.
