### ISSUE TITLE
cydo returned an error code (255)

### ISSUE THREAD

**Issue by ItzColdOutside** [pwn20wndstuff/Undecimus#256]
Hello everyone! I recently jaibroke my X on 11.3.1 and am unable to upgrade packages or install new tweaks. When trying to do so, I get this error code:

Sub-process /usr/libexec/cydia/cydo returned an error code (255)

Any suggestions?

(In full disclosure:  I'm on v2.2.0~b12. Previously, I was on v2.1.3 and getting both error 1 and error 2.  Was able to resolve them but now I seem to be stuck. Was hoping when I updated unc0ver that would possibly be it, but not yet.)

**Comment by atifchy** [comment]
Use Reinstall cydia option

**Comment by ItzColdOutside** [comment]
Solved it!

For anyone who might have the same issue, I found this is on Reddit:

_That’s a Cydo executable file error..it might mean something is missing or stuff like this. So restore rootFS should work I guess_

Restore RootFS did work. It took three tries, each time getting farther through the jailbreak process, but it finally worked. Good luck if you have the same issue!

**Comment by anupvadhul** [comment]
Nothing required, just re-jailbreak., just open either uncover or chimera and tap rejailbreak button.

**Comment by redraushan** [comment]
> Solved it!
> 
> For anyone who might have the same issue, I found this is on Reddit:
> 
> _That’s a Cydo executable file error..it might mean something is missing or stuff like this. So restore rootFS should work I guess_
> 
> The Restore RootFS option in unc0ver did work. It took three tries, each time getting farther through the jailbreak process, but it finally worked. Good luck if you have the same issue!

Restoring RootFS didn't work for me, having same issue again

**Comment by RaidLands** [comment]
same error and RootFS didn't worked

**Comment by electric-skeptic** [comment]
This morning I started seeing "Sub-process /usr/libexec/cydia/cydo returned an error code (255)", which I fixed just by setting the unc0ver option 'Reset Cydia Cache'.
If that hadn't resolved it I'd have attempted 'Reinstalled Cydia' or 'Restore RootFS' next though

**Comment by blueberrywaffle** [comment]
> same error and RootFS didn't worked

Did you find a solution @RaidLands? Having the same issue too. Have tried reinstall cydia option, and rootFS, neither are working for me

**Comment by schatzicat** [comment]
same issue here.  tried many things.  tried filza solution people have spoke about.  tried ssh method but couldn’t connect (may have to install open ssh in uncover options).  and tried this.  but this method of restore root removed all tweaks and even some apps. so now filza method impossible to try not as it is gone cant instal via cydia.    will try ssh method again later as i will allow open ssh via uncover options.  anyone! plz help!

**Comment by schatzicat** [comment]
also...this all started when a method of getting reprovision working but installing old version went around and i tried that

**Comment by shaded56** [comment]
Hi have the same issue. I’ve tried everything and I still get error 255. I was on unc0ver 11.4-12.4 but it got revoked so I installed the newest version of unc0ver which is 11.4-13.3. None of my tweaks work and restoring doesn’t help.

**Comment by aiz0013** [comment]
I Guess it's about the uncover update? gonna try rn to reinstall 11.4-12.4 uncover. and jailbreak again

**Comment by blueberrywaffle** [comment]
I found the solution, yeah its the new uncover update, if you dont have an A12 or A13 device you cant use v4.x.x, just find v3.8.0, rejailbreak and youll be fine, if you tried to use restore rootFS your tweaks will be gone but you just need to reinstall them

**Comment by aiz0013** [comment]
IT WORKED!!!!!!!! the older version 11.4-12.4 worksss!!!! the problem  for the errors is the new uncover release

**Comment by schatzicat** [comment]
got 3.8.0 but halfway get error unable to start cudia substrate

**Comment by aiz0013** [comment]
that'd work. mine working perfectly again

**Comment by RoshanOscarSah** [comment]
From where do I install downgraded uncover

**Comment by lliamc** [comment]
> From where do I install downgraded uncover

Type unc0ver 3.8.0 in google and click the first link (iosninja.io), scroll down, and click the proper release.

Here's a link to that page: https://iosninja.io/ipa-library/download-unc0ver-jailbreak-ios-12-iphone-ipad-ipod

**Comment by emmahaskins15** [comment]
Can confirm that switching to 3.8 is working for me, thanks for the tip!

**Comment by justanswerthequestion** [comment]
Where would I download uncover v3.8.0? I searched it, got sent to github, found the right version but it just downloads a file not an app that is useless on iOS

**Comment by lliamc** [comment]
> Where would I download uncover v3.8.0? I searched it, got sent to github, found the right version but it just downloads a file not an app that is useless on iOS


Bruv look two replies up....

> > From where do I install downgraded uncover
> 
> Type unc0ver 3.8.0 in google and click the first link (iosninja.io), scroll down, and click the proper release.
> 
> Here's a link to that page: https://iosninja.io/ipa-library/download-unc0ver-jailbreak-ios-12-iphone-ipad-ipod

**Comment by olbartek** [comment]
Switching to 3.8.0 also worked for me (RootFS did not work). 
You can also get all the releases from official github page https://github.com/pwn20wndstuff/Undecimus/releases

**Comment by b19g3r** [comment]
> I Guess it's about the uncover update? gonna try rn to reinstall 11.4-12.4 uncover. and jailbreak again

worked for me

**Comment by jb-ui** [comment]
> > I Guess it's about the uncover update? gonna try rn to reinstall 11.4-12.4 uncover. and jailbreak again
> 
> worked for me

may i ask how dis you install the uncover v. 3.8.0? what method did you use? thanks.

**Comment by jb-ui** [comment]
> Switching to 3.8.0 also worked for me (RootFS did not work).
> You can also get all the releases from official github page https://github.com/pwn20wndstuff/Undecimus/releases

may i ask how dis you install the uncover v. 3.8.0? what method did you use? thanks. cydia impactor does not work for me,free accounts do not install ipas. i hope you can reply:)

**Comment by vickey97** [comment]
> may i ask how dis you install the uncover v. 3.8.0? what method did you use? thanks. cydia impactor does not work for me,free accounts do not install ipas. i hope you can reply:)

Yeah same, impactor doesn't work neither does 3utools. Can anyone help us out? How to install IPA on iPhone which are not jailbroken?

**Comment by rcelus** [comment]
Just use AppCake or AltStore....to install the ipa’s!

**Comment by lliamc** [comment]
https://iosninja.io/ipa-library/download-unc0ver-jailbreak-ios-12-iphone-ipad-ipod

Click the link that says "Alternative: Tap to install (v3.8.0)"

**DO THIS FROM YOUR PHONE**

bada bing bada boom.

It's fascinating how many people ask for the same things that are answered just a couple of posts up...

**Comment by linronaldo** [comment]
> > same error and RootFS didn't worked
> 
> Did you find a solution @RaidLands? Having the same issue too. Have tried reinstall cydia option, and rootFS, neither are working for me

me neither...... :|

**Comment by linronaldo** [comment]
> https://iosninja.io/ipa-library/download-unc0ver-jailbreak-ios-12-iphone-ipad-ipod
> 
> Click the link that says "Alternative: Tap to install (v3.8.0)"
> 
> **DO THIS FROM YOUR PHONE**
> 
> bada bing bada boom.
> 
> It's fascinating how many people ask for the same things that are answered just a couple of posts up...

not works any more, because apple revoked it.

**Comment by linronaldo** [comment]
> Switching to 3.8.0 also worked for me (RootFS did not work).
> You can also get all the releases from official github page https://github.com/pwn20wndstuff/Undecimus/releases

hi, but a question comes: how to install it on mobile, since impactor woundnt work for many guys

**Comment by linronaldo** [comment]
> > Where would I download uncover v3.8.0? I searched it, got sent to github, found the right version but it just downloads a file not an app that is useless on iOS
> 
> Bruv look two replies up....
> 
> > > From where do I install downgraded uncover
> > 
> > 
> > Type unc0ver 3.8.0 in google and click the first link (iosninja.io), scroll down, and click the proper release.
> > Here's a link to that page: https://iosninja.io/ipa-library/download-unc0ver-jailbreak-ios-12-iphone-ipad-ipod

hi, solved? got an answer？

**Comment by ghost** [comment]
I downloaded unc0ver 3.8.0 from the repo and installed it using AppCake. Fixed it for me.

**Comment by linronaldo** [comment]
Hey thanks a lot , may I know what repo you indicated?


Thanks & BR
Freddie

Friday, February 21, 2020, 20:22 +0800 from notifications@github.com  <notifications@github.com>:

**Comment by karvinh** [comment]
I FOUND IT , @linronaldo and who ever is out there, this worked for me 
ok listen , First download app cake . Search https://iphonecake.com/app/ in safari download it. Next go in the app store and download document. Next go to IOS NINJA (https://iosninja.io/ipa-library/download-unc0ver-jailbreak-ios-12-iphone-ipad-ipod ) on your iphone not computer and install the 3.8.0 version. and install it into DOCUMENT. NOW go to your document and find the ipa file. click on it and download it into APP CAKE. it should install and there u go u have the 11-12.4 uncover version again. HURRY THE APP CAKE MIGHT GET UNCERTIFIDED soon . as of right now it works. hope this helps .

**Comment by karvinh** [comment]
> Hey thanks a lot , may I know what repo you indicated? Thanks & BR Freddie Friday, February 21, 2020, 20:22 +0800 from notifications@github.com <notifications@github.com>:
> […](#)
> I downloaded unc0ver 3.8.0 from the repo and installed it using AppCake. Fixed it for me. — You are receiving this because you commented. Reply to this email directly, view it on GitHub , or unsubscribe .

I FOUND IT , @linronaldo and who ever is out there, this worked for me 
ok listen , First download app cake . Search https://iphonecake.com/app/ in safari download it. Next go in the app store and download document. Next go to IOS NINJA (https://iosninja.io/ipa-library/download-unc0ver-jailbreak-ios-12-iphone-ipad-ipod ) on your iphone not computer and install the 3.8.0 version. and install it into DOCUMENT. NOW go to your document and find the ipa file. click on it and download it into APP CAKE. it should install and there u go u have the 11-12.4 uncover version again. HURRY THE APP CAKE MIGHT GET UNCERTIFIDED soon . as of right now it works. hope this helps .

**Comment by karvinh** [comment]
> Hey thanks a lot , may I know what repo you indicated? Thanks & BR Freddie Friday, February 21, 2020, 20:22 +0800 from notifications@github.com <notifications@github.com>:
> […](#)
> I downloaded unc0ver 3.8.0 from the repo and installed it using AppCake. Fixed it for me. — You are receiving this because you commented. Reply to this email directly, view it on GitHub , or unsubscribe .

helping a brotha out

**Comment by ghost** [comment]
I used this repo: https://github.com/pwn20wndstuff/Undecimus/releases. The iosninja download should work too, though.

**Comment by chiboul** [comment]
> > Hey thanks a lot , may I know what repo you indicated? Thanks & BR Freddie Friday, February 21, 2020, 20:22 +0800 from [notifications@github.com](mailto:notifications@github.com) [notifications@github.com](mailto:notifications@github.com):
> > […](#)
> > I downloaded unc0ver 3.8.0 from the repo and installed it using AppCake. Fixed it for me. — You are receiving this because you commented. Reply to this email directly, view it on GitHub , or unsubscribe .
> 
> I FOUND IT , @linronaldo and who ever is out there, this worked for me
> ok listen , First download app cake . Search https://iphonecake.com/app/ in safari download it. Next go in the app store and download document. Next go to IOS NINJA (https://iosninja.io/ipa-library/download-unc0ver-jailbreak-ios-12-iphone-ipad-ipod ) on your iphone not computer and install the 3.8.0 version. and install it into DOCUMENT. NOW go to your document and find the ipa file. click on it and download it into APP CAKE. it should install and there u go u have the 11-12.4 uncover version again. HURRY THE APP CAKE MIGHT GET UNCERTIFIDED soon . as of right now it works. hope this helps .

Well, the installation never finishes and furthermore iOS ninja is down.
But the same steps with the file downloaded from pwn github resulted in nothing.

There is literally no working way to install a downgraded version for now...

**Comment by karvinh** [comment]
> > > Hey thanks a lot , may I know what repo you indicated? Thanks & BR Freddie Friday, February 21, 2020, 20:22 +0800 from [notifications@github.com](mailto:notifications@github.com) [notifications@github.com](mailto:notifications@github.com):
> > > […](#)
> > > I downloaded unc0ver 3.8.0 from the repo and installed it using AppCake. Fixed it for me. — You are receiving this because you commented. Reply to this email directly, view it on GitHub , or unsubscribe .
> > 
> > 
> > I FOUND IT , @linronaldo and who ever is out there, this worked for me
> > ok listen , First download app cake . Search https://iphonecake.com/app/ in safari download it. Next go in the app store and download document. Next go to IOS NINJA (https://iosninja.io/ipa-library/download-unc0ver-jailbreak-ios-12-iphone-ipad-ipod ) on your iphone not computer and install the 3.8.0 version. and install it into DOCUMENT. NOW go to your document and find the ipa file. click on it and download it into APP CAKE. it should install and there u go u have the 11-12.4 uncover version again. HURRY THE APP CAKE MIGHT GET UNCERTIFIDED soon . as of right now it works. hope this helps .
> 
> Well, the installation never finishes and furthermore iOS ninja is down.
> But the same steps with the file downloaded from pwn github resulted in nothing.
> 
> There is literally no working way to install a downgraded version for now...

Here’s a video

**Comment by chiboul** [comment]
> > > > Hey thanks a lot , may I know what repo you indicated? Thanks & BR Freddie Friday, February 21, 2020, 20:22 +0800 from [notifications@github.com](mailto:notifications@github.com) [notifications@github.com](mailto:notifications@github.com):
> > > > […](#)
> > > > I downloaded unc0ver 3.8.0 from the repo and installed it using AppCake. Fixed it for me. — You are receiving this because you commented. Reply to this email directly, view it on GitHub , or unsubscribe .
> > > 
> > > 
> > > I FOUND IT , @linronaldo and who ever is out there, this worked for me
> > > ok listen , First download app cake . Search https://iphonecake.com/app/ in safari download it. Next go in the app store and download document. Next go to IOS NINJA (https://iosninja.io/ipa-library/download-unc0ver-jailbreak-ios-12-iphone-ipad-ipod ) on your iphone not computer and install the 3.8.0 version. and install it into DOCUMENT. NOW go to your document and find the ipa file. click on it and download it into APP CAKE. it should install and there u go u have the 11-12.4 uncover version again. HURRY THE APP CAKE MIGHT GET UNCERTIFIDED soon . as of right now it works. hope this helps .
> > 
> > 
> > Well, the installation never finishes and furthermore iOS ninja is down.
> > But the same steps with the file downloaded from pwn github resulted in nothing.
> > There is literally no working way to install a downgraded version for now...
> 
> Here’s a video

Fck me, I managed to get it working !
Did it without the Document app and directly through the AppCake webapp (was previsously done from the Cydia's AppCake).

**Comment by someoneunderbed** [comment]
Guys just found a way to install unc0ver 3.8.0 b1 just one tap (without computer)
Here's the link:
https://apps.pulandres.me/

**Comment by linronaldo** [comment]
tried many times, cant download it on mobile phone through safari， the wetransfer made me suffered. 


Thanks & BR
Freddie

Saturday, February 22, 2020, 04:57 +0800 from notifications@github.com  <notifications@github.com>:

**Comment by jb-ui** [comment]
i finally solved it. thank you. cydo error 255 gone. cydia is working fine
and installing tweaks now. i did this again and i followed this
instructions👉🏻 (i hope this will help you guys out there too. just redo
it if it did not work the first time. maybe you missed something? thank you
again good kind sir for sharing this:))ok listen , First download app cake
. Search  https://iphonecake.com/app/ in safari download it. Next go in the
app store and download document. Next go to IOS NINJA (
https://iosninja.io/ipa-library/download-unc0ver-jailbreak-ios-12-iphone-ipad-ipod
)
on your iphone not computer and install the 3.8.0 version. and install it
into DOCUMENT. NOW go to your document and find the ipa file. click on it
and download it into APP CAKE. it should install and there u go u have the
11-12.4 uncover version again. HURRY THE APP CAKE MIGHT GET UNCERTIFIDED
soon . as of right now it works. hope this helps .

**Comment by Jokerlin1** [comment]
> Hi have the same issue. I’ve tried everything and I still get error 255. I was on unc0ver 11.4-12.4 but it got revoked so I installed the newest version of unc0ver which is 11.4-13.3. None of my tweaks work and restoring doesn’t help.

the older version can solve，you can download at unc0ver.dev

**Comment by jb-ui** [comment]
please read this . i hope this helps. 👉🏻 i finally solved it. thank you.
cydo error 255 gone. cydia is working fine and installing tweaks now. i did
this again and i followed this instructions👉🏻 (i hope this will help you
guys out there too. just redo it if it did not work the first time. maybe
you missed something? thank you again good kind sir for sharing this:))ok
listen , First download app cake . Search  https://iphonecake.com/app/ in
safari download it. Next go in the app store and download document. Next go
to IOS NINJA (
https://iosninja.io/ipa-library/download-unc0ver-jailbreak-ios-12-iphone-ipad-ipod
)
on your iphone not computer and install the 3.8.0 version. and install it
into DOCUMENT. NOW go to your document and find the ipa file. click on it
and download it into APP CAKE. it should install and there u go u have the
11-12.4 uncover version again. HURRY THE APP CAKE MIGHT GET UNCERTIFIDED
soon . as of right now it works. hope this helps .

**Comment by idb-** [comment]
> Next go in the app store and download document.

Can you be a bit more clear on this step? Searching for "document" in the app store yields quite a few results.

**Comment by karvinh** [comment]
Document by readdle on the App Store

**Comment by jb-ui** [comment]
the certificate of appcake cannot be verified anymore. it started yesterday
with me. anyone having a situation like this too? thanks.

**Comment by jb-ui** [comment]
the certificate of appcake and uncover from the profile in the settings of
my iphone cannot be verified anymore. it started yesterday with me. anyone
having a situation like this too? thanks.

**Comment by linronaldo** [comment]
[Certificate invalid CONFIRMED]yes all this certificate (Toyota Motor Finance(China) Co. Ltd) related app has become invalid, such as unc0ver and others jailbreak app


Thanks & BR
Freddie

Wednesday, February 26, 2020, 12:11 +0800 from notifications@github.com  <notifications@github.com>:
>the certificate of appcake and uncover from the profile in the settings of
>my iphone cannot be verified anymore. it started yesterday with me. anyone
>having a situation like this too? thanks.
>
>

**Comment by jb-ui** [comment]
so there is no fix for this anymore? only altstore ? thanks.
