### ISSUE TITLE
Failed to extract bootstrap

### ISSUE THREAD

**Issue by Machenka** [pwn20wndstuff/Undecimus#705]
iPhone 6s - iOS 12.1.1 - unc0ver 3.0.0 b41

This issue has been present on my 6s on all the unc0ver iOS 12 betas so far making it impossible to complete the jailbreak. It seems the "failed to extract bootstrap" popup occurs at the same part of the jailbreak everytime, while working on the libssl package. I have restored RootFS before each and every attempt to ensure a clean device.

I have attached the last few lines of the visible log below, but please get back to me if you need me to try to export the diagnostics data or if I in some other way can assist in identifying the core issue.

**To Reproduce**
Initiate jailbreak. Will fail when reaching 'libssl' package.

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: iPhone 6s
 - unc0ver Version: 3.0.0 b41

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
[*] runCommandv(255): update-alternatives: using /usr/libexec/ldid_wrapper to provide /usr/bin/ldid (ldid) in auto mode
[*] runCommandv(255): Setting up com.ps.letmeblock (0.0.1) ...
[*] runCommandv(255): Setting up readline (7.0.5-2) ...
[*] runCommandv(255): dpkg: ldid: dependency problems, but configuring anyway as you requested:
[*] runCommandv(255): ldid depends on libssl1.0; however:
[*] runCommandv(255): Package libssl1.0 is not installed.
[*] runCommandv(255):
[*] runCommandv(255): Setting up ldid (2:2.1.1+elucubratus1) ...
[*] runCommandv(255): Errors were encountered while processing:
[*] runCommandv(255): /var/containers/Bundle/Application/D7962853-D9D7-476D-900F-304FF66C409E/Undecimus.app/apt/libssl1.0_1.0.2q-1_iphoneos-arm.deb
[*] runCommandv(255) completed with exit status 1
[*] __assert(2:installDebs(debsToInstall, true))@JailbreakViewController.m:1693[jailbreak]

**Comment by chambaw** [comment]
Open

**Comment by moks84** [comment]
![img_2298](https://user-images.githubusercontent.com/48246734/53804953-8c48e880-3f51-11e9-86cc-05db9d8edc6a.PNG)
I'm receiving the same error. ios 12.1.2 iphone 5S

**Comment by Krobix** [comment]
Somewhat happens to me on iPhone six after I jailbroke, attempted to install a certain BootLogo, and iOS... unjailbroke itself? Now I get this error when retrying. Might try RootFS later.

**Comment by moks84** [comment]
The way I fixed it.
1- set Airplane mode on, Turn off load tweaks and load daemons.
2- restore the Rootfs, Jailbreak till it successfully restored, Device will restart now.
3- Turn Off the restore Rootfs and Jailbreak, it will restart will it take snapshot.
4- Jailbreak again until the bootstrap installments succeed.
5- Jailbreak now to install Cydia (make sure you keep the option of load tweaks and daemons off)
6- You should find Cydia on the board, now enable the load tweaks and daemons then jailbreak.

**Comment by vitalik2187836** [comment]
I want it to be true but this doesn’t help in every situation. For example i have an error on line 1711 and i tried with deamons on and off, reload system deamons on and off, airplane mode on and off and getting the same error.

**Comment by lace22** [comment]
**After trying**

> 
> 
> The way I fixed it.
> 1- set Airplane mode on, Turn off load tweaks and load daemons.
> 2- restore the Rootfs, Jailbreak till it successfully restored, Device will restart now.
> 3- Turn Off the restore Rootfs and Jailbreak, it will restart will it take snapshot.
> 4- Jailbreak again until the bootstrap installments succeed.
> 5- Jailbreak now to install Cydia (make sure you keep the option of load tweaks and daemons off)
> 6- You should find Cydia on the board, now enable the load tweaks and daemons then jailbreak.

Now it gets stuck on `[*] Extracting Cydia...`
(Tried several times)

**Comment by Machenka** [comment]
OP here. I still have this annoying issue. Still happening on the libssl step, so I still haven't managed to jailbreak my iPhone 6S successfully. If I can assist with logs or similar just hit me up.

**Comment by Machenka** [comment]
@moks84: I have tried your suggestion but still receive the bootstrap error on the libssl task. Is it understood correctly that load tweaks and daemons should be off until step 6. In step 4 you do not mention it so I’m not sure about whether it should be reactivated in that step and then deactivated again in step 5 although that wouldn’t really make any sense?

I wonder why the error constantly occurs on the libssl part in my device as I haven’t seen anybody else mentioning it to fail on that specific component. If I could just pass that step or something it would be awesome. It seems like there’s an earlier version it tries to replace, perhaps a leftover from an earlier jailbreak but I can’t see what I can do about that component specifically...sigh...

**Comment by moks84** [comment]
There are release for unc0ver ~b48, please give it a try, it had a good improvements.
insure the airplane is on until cydia is installed.
switch back the daemons and tweaks only after cydia installation (step 6), and insure they are turned off for all steps until Cydia is installed.

**Comment by killerlooks10** [comment]
I would suggest you to watch this video. hope this will solve your problem
https://www.youtube.com/watch?v=0mdX-PcsZpk&t=195s
